version: "3"
services:
  neo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neo
    ports:
      - "50012:50012"
    restart: unless-stopped
    volumes:
      - ./:/contracts/
